/**
 * CozyCatKitchen — Order Logger
 * --------------------------------
 * This script receives bill data from the e-bill webpage and
 * appends each order as a new row in this Google Sheet.
 *
 * SETUP: See SETUP_INSTRUCTIONS.md for step-by-step deployment.
 */

/* ============================================================
 * COLUMN DEFINITIONS — single source of truth
 * ------------------------------------------------------------
 * Keys are the JS names used throughout this file.
 * Values are the exact header strings that must appear in row 1.
 * Adding a new column = add it here + add it to ORDER_HEADERS.
 * See docs/SCHEMA.md for column meanings, types, and examples.
 * ============================================================ */
var ORDER_COLS = {
  billNo:            'Bill No',
  date:              'Date',
  name:              'Customer Name',
  phone:             'Phone',
  email:             'Email',
  address:           'Address',
  itemsSummary:      'Items Summary',
  totalItems:        'Total Items',
  deliveryCharges:   'Delivery Charges',
  totalAmount:       'Total Amount',
  paymentStatus:     'Payment Status',
  dispatchDate:      'Dispatch Date',
  remarks:           'Remarks',
  generatedBy:       'Generated By',
  paymentProof:      'Payment Proof',
  fulfillmentStatus: 'Fulfillment Status',
  trackingLink:      'Tracking Link',
  mapLink:           'Map Link',
  deliveryType:      'Delivery Type',
  shareToken:        'Share Token'
};

// Ordered header row written when a new sheet is initialised.
// Must contain every value from ORDER_COLS, in the desired column order.
var ORDER_HEADERS = [
  'Bill No', 'Date', 'Customer Name', 'Phone', 'Email',
  'Address', 'Items Summary', 'Total Items', 'Delivery Charges',
  'Total Amount', 'Payment Status', 'Dispatch Date', 'Remarks', 'Generated By',
  'Payment Proof', 'Fulfillment Status', 'Tracking Link', 'Map Link', 'Delivery Type', 'Share Token'
];

var CUSTOMER_COLS = {
  name:          'Name',
  phone:         'Phone',
  address:       'Address',
  email:         'Email',
  notes:         'Notes',
  lastOrderDate: 'LastOrderDate',
  totalOrders:   'TotalOrders'
};

var CUSTOMER_HEADERS = ['Name', 'Phone', 'Address', 'Email', 'Notes', 'LastOrderDate', 'TotalOrders'];

/* ============================================================
 * COLUMN MAP HELPERS
 * ============================================================ */

// Returns { fieldKey: 0-based-index, ... } by reading the sheet's header row.
// Throws if any expected column is absent — surfaces a clear error instead of
// silently reading the wrong column.
function buildColMap_(sheet, colDef) {
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  var idx = {};
  for (var i = 0; i < headers.length; i++) {
    idx[String(headers[i]).trim()] = i;
  }
  var map = {};
  for (var key in colDef) {
    var h = colDef[key];
    if (!(h in idx)) {
      throw new Error('Column "' + h + '" not found in "' + sheet.getName() + '" — check docs/SCHEMA.md');
    }
    map[key] = idx[h];
  }
  return map;
}

// Converts a raw sheet row (array) to a plain order object.
function rowToOrder_(r, cm) {
  return {
    billNo:            r[cm.billNo],
    date:              r[cm.date],
    name:              r[cm.name],
    phone:             r[cm.phone],
    email:             r[cm.email],
    address:           r[cm.address],
    itemsSummary:      r[cm.itemsSummary],
    totalItems:        r[cm.totalItems],
    deliveryCharges:   r[cm.deliveryCharges],
    totalAmount:       r[cm.totalAmount],
    paymentStatus:     r[cm.paymentStatus],
    dispatchDate:      r[cm.dispatchDate],
    remarks:           r[cm.remarks],
    generatedBy:       r[cm.generatedBy],
    paymentProof:      r[cm.paymentProof],
    fulfillmentStatus: r[cm.fulfillmentStatus],
    trackingLink:      r[cm.trackingLink],
    mapLink:           r[cm.mapLink],
    deliveryType:      r[cm.deliveryType],
    shareToken:        r[cm.shareToken]
  };
}

// Builds an ordered array suitable for appendRow() from a map of
// { 'Header String': value }. Columns absent from the map get ''.
function buildRow_(valuesByHeader) {
  return ORDER_HEADERS.map(function(h) {
    return h in valuesByHeader ? valuesByHeader[h] : '';
  });
}

// Converts a 0-based column index to a spreadsheet letter (A, B, …, AA, …).
function colLetter_(idx) {
  var letter = '';
  var n = idx + 1;
  while (n > 0) {
    var rem = (n - 1) % 26;
    letter = String.fromCharCode(65 + rem) + letter;
    n = Math.floor((n - 1) / 26);
  }
  return letter;
}

/* ============================================================
 * HTTP ENTRY POINTS
 * ============================================================ */

function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);

    // Public: authenticate and hand back a signed session token.
    if (data.action === 'login') {
      return login_(data.user || '', data.pass || '');
    }

    // Every other POST is a privileged write — require a valid session token.
    if (!verifyToken_(data.auth)) {
      return jsonResponse({ status: 'error', message: 'Unauthorized' });
    }

    if (data.action === 'uploadProof') {
      return uploadPaymentProof(data);
    }

    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();

    // Add header row if sheet is empty
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(ORDER_HEADERS);
    }

    sheet.appendRow(buildRow_({
      'Bill No':           data.billNo || '',
      'Date':              data.dateStr || '',
      'Customer Name':     data.name || '',
      'Phone':             data.phone || '',
      'Email':             data.email || '',
      'Address':           data.address || '',
      'Items Summary':     data.itemsSummary || '',
      'Total Items':       data.totalItems || 0,
      'Delivery Charges':  data.deliveryCharges || 0,
      'Total Amount':      data.totalAmount || 0,
      'Payment Status':    data.paymentStatus || 'Pending',
      'Dispatch Date':     data.dispatchDate || '',
      'Remarks':           data.remarks || '',
      'Generated By':      data.generatedBy || '',
      'Map Link':          data.mapLink || '',
      'Delivery Type':     data.deliveryType || '',
      'Share Token':       data.shareToken || ''
      // Payment Proof, Fulfillment Status, Tracking Link start empty
    }));

    upsertCustomer(data.name || '', data.phone || '', data.email || '', data.address || '', data.dateStr || '');

    return ContentService.createTextOutput(JSON.stringify({ status: 'success' }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    return ContentService.createTextOutput(JSON.stringify({ status: 'error', message: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  }
}

function doGet(e) {
  var action = (e && e.parameter) ? e.parameter.action : null;

  // Public endpoint: customers open their own order tracking link, which is
  // already scoped by the per-order share token — no login required.
  if (action === 'getOrderByBill') {
    return getOrderByBill(e.parameter.billNo || '', e.parameter.token || '');
  }

  // Public endpoint: the app reports client-side errors here. Kept public so
  // failures that happen before/without login are still captured. Using GET
  // also means an older deployment that doesn't know this action just returns
  // its default text — never a spurious write.
  if (action === 'clientError') {
    return logClientError_(e.parameter);
  }

  // Everything below reads or writes business data (incl. customer PII) and
  // requires a valid session token (issued by the login action).
  var PROTECTED = { orders: 1, customers: 1, updateStatus: 1, updateFulfillment: 1 };
  if (PROTECTED[action] && !verifyToken_(e.parameter.auth)) {
    return jsonResponse({ status: 'error', message: 'Unauthorized' });
  }

  if (action === 'orders') {
    return getOrders(e.parameter.search || '', parseInt(e.parameter.limit) || 50);
  }

  if (action === 'updateStatus') {
    return updateStatus(e.parameter.billNo || '', e.parameter.status || '');
  }

  if (action === 'updateFulfillment') {
    return updateFulfillment(
      e.parameter.billNo || '',
      e.parameter.fulfillmentStatus || '',
      e.parameter.trackingLink || ''
    );
  }

  if (action === 'customers') {
    return getCustomers();
  }

  return ContentService.createTextOutput('CozyCatKitchen order logger is running.');
}

/* ============================================================
 * ORDERS — read & write
 * ============================================================ */

function getOrders(search, limit) {
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    var lastRow = sheet.getLastRow();
    if (lastRow <= 1) return jsonResponse({ status: 'success', orders: [] });

    var cm = buildColMap_(sheet, ORDER_COLS);
    var data = sheet.getRange(2, 1, lastRow - 1, sheet.getLastColumn()).getValues();
    var s = search.toLowerCase();
    var filtered = s ? data.filter(function(r) {
      return String(r[cm.billNo]).toLowerCase().indexOf(s) > -1 ||
             String(r[cm.name]).toLowerCase().indexOf(s) > -1;
    }) : data;

    // Most recent first, capped at limit
    var orders = filtered.slice().reverse().slice(0, limit).map(function(r) {
      return rowToOrder_(r, cm);
    });

    return jsonResponse({ status: 'success', orders: orders });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

function updateStatus(billNo, status) {
  var valid = ['Pending', 'Paid', 'Refunded', 'Failed', 'Cancelled'];
  if (!billNo || valid.indexOf(status) === -1) {
    return jsonResponse({ status: 'error', message: 'Invalid bill number or status' });
  }
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    var lastRow = sheet.getLastRow();
    if (lastRow <= 1) return jsonResponse({ status: 'error', message: 'Bill not found' });

    var cm = buildColMap_(sheet, ORDER_COLS);
    var billNos = sheet.getRange(2, cm.billNo + 1, lastRow - 1, 1).getValues();
    var rowIndex = -1;
    for (var i = 0; i < billNos.length; i++) {
      if (String(billNos[i][0]) === String(billNo)) { rowIndex = i + 2; break; }
    }
    if (rowIndex === -1) return jsonResponse({ status: 'error', message: 'Bill not found' });

    sheet.getRange(rowIndex, cm.paymentStatus + 1).setValue(status);
    return jsonResponse({ status: 'success' });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

function uploadPaymentProof(data) {
  var billNo = data.billNo || '';
  var imageBase64 = data.imageBase64 || '';
  var mimeType = data.mimeType || 'image/jpeg';
  if (!billNo || !imageBase64) {
    return jsonResponse({ status: 'error', message: 'Missing billNo or image data' });
  }

  var folderName = 'CCK Payment Screenshots';
  var folders = DriveApp.getFoldersByName(folderName);
  var folder = folders.hasNext() ? folders.next() : DriveApp.createFolder(folderName);

  var ext = mimeType.split('/')[1] || 'jpg';
  var blob = Utilities.newBlob(Utilities.base64Decode(imageBase64), mimeType, billNo + '-proof.' + ext);
  var file = folder.createFile(blob);
  file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  var link = file.getUrl();

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var lastRow = sheet.getLastRow();
  if (lastRow > 1) {
    var cm = buildColMap_(sheet, ORDER_COLS);
    var billNos = sheet.getRange(2, cm.billNo + 1, lastRow - 1, 1).getValues();
    for (var i = 0; i < billNos.length; i++) {
      if (String(billNos[i][0]) === String(billNo)) {
        sheet.getRange(i + 2, cm.paymentProof + 1).setValue(link);
        break;
      }
    }
  }

  return jsonResponse({ status: 'success', link: link });
}

function getOrderByBill(billNo, token) {
  if (!billNo || !token) {
    return jsonResponse({ status: 'error', message: 'Invalid link' });
  }
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    var lastRow = sheet.getLastRow();
    if (lastRow <= 1) return jsonResponse({ status: 'error', message: 'Order not found' });

    var cm = buildColMap_(sheet, ORDER_COLS);
    var data = sheet.getRange(2, 1, lastRow - 1, sheet.getLastColumn()).getValues();
    for (var i = 0; i < data.length; i++) {
      var r = data[i];
      if (String(r[cm.billNo]) === String(billNo)) {
        if (String(r[cm.shareToken]) !== String(token)) {
          return jsonResponse({ status: 'error', message: 'Invalid link' });
        }
        return jsonResponse({
          status: 'success',
          order: {
            billNo:            r[cm.billNo],
            date:              r[cm.date],
            name:              r[cm.name],
            itemsSummary:      r[cm.itemsSummary],
            totalItems:        r[cm.totalItems],
            deliveryCharges:   r[cm.deliveryCharges],
            totalAmount:       r[cm.totalAmount],
            paymentStatus:     r[cm.paymentStatus],
            dispatchDate:      r[cm.dispatchDate],
            fulfillmentStatus: r[cm.fulfillmentStatus],
            trackingLink:      r[cm.trackingLink]
          }
        });
      }
    }
    return jsonResponse({ status: 'error', message: 'Order not found' });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

function updateFulfillment(billNo, fulfillmentStatus, trackingLink) {
  var valid = ['Packed', 'Booked', 'Picked Up', 'Delivered'];
  if (!billNo || valid.indexOf(fulfillmentStatus) === -1) {
    return jsonResponse({ status: 'error', message: 'Invalid bill number or fulfillment status' });
  }
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
    var lastRow = sheet.getLastRow();
    if (lastRow <= 1) return jsonResponse({ status: 'error', message: 'Bill not found' });

    var cm = buildColMap_(sheet, ORDER_COLS);
    var billNos = sheet.getRange(2, cm.billNo + 1, lastRow - 1, 1).getValues();
    var rowIndex = -1;
    for (var i = 0; i < billNos.length; i++) {
      if (String(billNos[i][0]) === String(billNo)) { rowIndex = i + 2; break; }
    }
    if (rowIndex === -1) return jsonResponse({ status: 'error', message: 'Bill not found' });

    sheet.getRange(rowIndex, cm.fulfillmentStatus + 1).setValue(fulfillmentStatus);
    if (trackingLink) sheet.getRange(rowIndex, cm.trackingLink + 1).setValue(trackingLink);
    return jsonResponse({ status: 'success' });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

function jsonResponse(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

/* ============================================================
 * AUTH — per-user login with stateless, HMAC-signed tokens
 * ------------------------------------------------------------
 * Users live in a "Users" sheet tab (username, salt, passwordHash,
 * role, active). Passwords are stored only as SHA-256(password + salt).
 * On login we return a token "<payload>.<signature>" where payload is
 * base64url({u, r, exp}) and signature is HMAC-SHA256(payload, SERVER_SECRET).
 * The token is self-contained (stateless) — no session table to keep.
 *
 * ONE-TIME SETUP (run these from the Apps Script editor, once):
 *   1. setupServerSecret()          — generates the signing secret
 *   2. setupUser('Aditya',   'a-strong-password', 'admin')
 *      setupUser('Priyanka', 'a-strong-password', 'staff')
 * Re-run setupUser any time to reset a password. To disable someone,
 * set their "active" cell in the Users sheet to FALSE.
 * ============================================================ */

var TOKEN_TTL_MS = 12 * 60 * 60 * 1000; // 12 hours

function getServerSecret_() {
  var s = PropertiesService.getScriptProperties().getProperty('SERVER_SECRET');
  if (!s) throw new Error('SERVER_SECRET is not set — run setupServerSecret() once.');
  return s;
}

function b64url_(bytes) {
  return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/, '');
}

function b64urlEncodeStr_(str) {
  return b64url_(Utilities.newBlob(str).getBytes());
}

function b64urlDecodeStr_(s) {
  return Utilities.newBlob(Utilities.base64DecodeWebSafe(s)).getDataAsString();
}

function hmac_(message) {
  return b64url_(Utilities.computeHmacSha256Signature(message, getServerSecret_()));
}

// Length-safe comparison that avoids leaking timing per-character.
function constantEquals_(a, b) {
  a = String(a); b = String(b);
  if (a.length !== b.length) return false;
  var r = 0;
  for (var i = 0; i < a.length; i++) r |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return r === 0;
}

function issueToken_(username, role) {
  var payload = b64urlEncodeStr_(JSON.stringify({ u: username, r: role, exp: Date.now() + TOKEN_TTL_MS }));
  return payload + '.' + hmac_(payload);
}

function verifyToken_(token) {
  if (!token) return null;
  var parts = String(token).split('.');
  if (parts.length !== 2) return null;
  if (!constantEquals_(parts[1], hmac_(parts[0]))) return null;
  var payload;
  try { payload = JSON.parse(b64urlDecodeStr_(parts[0])); } catch (err) { return null; }
  if (!payload || !payload.exp || Date.now() > payload.exp) return null;
  return payload; // { u, r, exp }
}

function usersSheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sh = ss.getSheetByName('Users');
  if (!sh) {
    sh = ss.insertSheet('Users');
    sh.appendRow(['username', 'salt', 'passwordHash', 'role', 'active']);
  }
  return sh;
}

function hashPassword_(password, salt) {
  return b64url_(Utilities.computeDigest(
    Utilities.DigestAlgorithm.SHA_256, String(password) + String(salt), Utilities.Charset.UTF_8));
}

function findUser_(username) {
  var sh = usersSheet_();
  var last = sh.getLastRow();
  if (last <= 1) return null;
  var rows = sh.getRange(2, 1, last - 1, 5).getValues();
  var uname = String(username).trim().toLowerCase();
  for (var i = 0; i < rows.length; i++) {
    if (String(rows[i][0]).trim().toLowerCase() === uname) {
      return { username: rows[i][0], salt: rows[i][1], hash: rows[i][2], role: rows[i][3], active: rows[i][4] };
    }
  }
  return null;
}

function login_(username, password) {
  var u = findUser_(username);
  var active = u && !(u.active === false || String(u.active).toLowerCase() === 'false');
  // Verify the password even on unknown users so response timing doesn't reveal
  // whether the username exists.
  var salt = u ? u.salt : 'no-such-user';
  var storedHash = u ? String(u.hash) : '';
  var ok = active && constantEquals_(hashPassword_(password, salt), storedHash);
  if (!ok) {
    return jsonResponse({ status: 'error', message: 'Invalid username or password' });
  }
  return jsonResponse({ status: 'success', token: issueToken_(u.username, u.role), user: u.username, role: u.role });
}

/**
 * ONE-TIME SETUP — generate the token-signing secret. Safe to re-run; it only
 * creates the secret if one doesn't already exist (re-running won't log people out).
 */
function setupServerSecret() {
  var props = PropertiesService.getScriptProperties();
  if (!props.getProperty('SERVER_SECRET')) {
    props.setProperty('SERVER_SECRET', Utilities.getUuid() + Utilities.getUuid());
    Logger.log('SERVER_SECRET generated.');
  } else {
    Logger.log('SERVER_SECRET already set — left unchanged.');
  }
}

/**
 * Create or reset a user. Run from the editor:
 *   setupUser('Aditya', 'their-password', 'admin')
 * Roles are free-form ('admin' / 'staff'); the app treats 'admin' as full access.
 */
function setupUser(username, password, role) {
  if (!username || !password) throw new Error('username and password are required');
  var sh = usersSheet_();
  var salt = Utilities.getUuid();
  var hash = hashPassword_(password, salt);
  var row = [username, salt, hash, role || 'staff', true];
  var last = sh.getLastRow();
  var existing = last > 1 ? sh.getRange(2, 1, last - 1, 1).getValues() : [];
  var uname = String(username).trim().toLowerCase();
  for (var i = 0; i < existing.length; i++) {
    if (String(existing[i][0]).trim().toLowerCase() === uname) {
      sh.getRange(i + 2, 1, 1, 5).setValues([row]);
      Logger.log('Updated user ' + username);
      return;
    }
  }
  sh.appendRow(row);
  Logger.log('Created user ' + username);
}

/* ============================================================
 * CUSTOMERS
 * ============================================================ */

/**
 * Returns all customers from the Customers sheet tab.
 */
function getCustomers() {
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var cs = ss.getSheetByName('Customers');
    if (!cs || cs.getLastRow() <= 1) return jsonResponse({ status: 'success', customers: [] });
    var cm = buildColMap_(cs, CUSTOMER_COLS);
    var rows = cs.getRange(2, 1, cs.getLastRow() - 1, cs.getLastColumn()).getValues();
    var customers = rows.filter(function(r) { return String(r[cm.name]).trim(); }).map(function(r) {
      return {
        name:          r[cm.name],
        phone:         r[cm.phone],
        address:       r[cm.address],
        email:         r[cm.email],
        notes:         r[cm.notes],
        lastOrderDate: r[cm.lastOrderDate],
        totalOrders:   r[cm.totalOrders]
      };
    });
    return jsonResponse({ status: 'success', customers: customers });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

/**
 * Creates or updates a customer record in the Customers sheet.
 * Matched by name (case-insensitive). Updates phone/email/address
 * with the latest values and increments the order count.
 */
function upsertCustomer(name, phone, email, address, orderDate) {
  if (!String(name).trim()) return;
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var cs = ss.getSheetByName('Customers');
    if (!cs) {
      cs = ss.insertSheet('Customers');
      cs.appendRow(CUSTOMER_HEADERS);
    }
    var cm = buildColMap_(cs, CUSTOMER_COLS);
    var nameLower = String(name).trim().toLowerCase();
    var lastRow = cs.getLastRow();
    if (lastRow > 1) {
      var names = cs.getRange(2, cm.name + 1, lastRow - 1, 1).getValues();
      for (var i = 0; i < names.length; i++) {
        if (String(names[i][0]).trim().toLowerCase() === nameLower) {
          var row = i + 2;
          if (phone)   cs.getRange(row, cm.phone + 1).setValue(phone);
          if (address) cs.getRange(row, cm.address + 1).setValue(address);
          if (email)   cs.getRange(row, cm.email + 1).setValue(email);
          cs.getRange(row, cm.lastOrderDate + 1).setValue(orderDate || '');
          var prev = cs.getRange(row, cm.totalOrders + 1).getValue() || 0;
          cs.getRange(row, cm.totalOrders + 1).setValue(Number(prev) + 1);
          return;
        }
      }
    }
    cs.appendRow([String(name).trim(), phone || '', address || '', email || '', '', orderDate || '', 1]);
  } catch (err) {
    Logger.log('upsertCustomer error: ' + err.toString());
  }
}

/**
 * ONE-TIME MIGRATION — run once from the Apps Script editor to:
 *   1. Create (or recreate) the Customers sheet tab
 *   2. Add column headers
 *   3. Backfill all unique customers from the existing Orders sheet
 *
 * Safe to re-run — it clears and rebuilds the sheet each time.
 */
function migrateCustomersFromOrders() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var cs = ss.getSheetByName('Customers');
  if (!cs) {
    cs = ss.insertSheet('Customers');
  } else {
    cs.clearContents();
  }
  cs.appendRow(CUSTOMER_HEADERS);

  var os = ss.getActiveSheet();
  var lastRow = os.getLastRow();
  if (lastRow <= 1) { Logger.log('No orders to migrate.'); return; }

  var cm = buildColMap_(os, ORDER_COLS);
  var data = os.getRange(2, 1, lastRow - 1, os.getLastColumn()).getValues();
  var map = {};
  for (var i = 0; i < data.length; i++) {
    var r = data[i];
    var rawName = String(r[cm.name]).trim();
    if (!rawName) continue;
    var key = rawName.toLowerCase();
    var dateVal = r[cm.date] ? new Date(r[cm.date]) : null;
    if (!map[key]) {
      map[key] = {
        name: rawName,
        phone: String(r[cm.phone]).trim(),
        address: String(r[cm.address]).trim(),
        email: String(r[cm.email]).trim(),
        lastDate: dateVal,
        count: 1
      };
    } else {
      map[key].count++;
      if (dateVal && (!map[key].lastDate || dateVal > map[key].lastDate)) {
        map[key].lastDate = dateVal;
        if (r[cm.phone])   map[key].phone   = String(r[cm.phone]).trim();
        if (r[cm.address]) map[key].address = String(r[cm.address]).trim();
        if (r[cm.email])   map[key].email   = String(r[cm.email]).trim();
      }
    }
  }

  var rows = [];
  for (var k in map) {
    var c = map[k];
    var dateStr = c.lastDate ? Utilities.formatDate(c.lastDate, Session.getScriptTimeZone(), 'dd/MM/yyyy') : '';
    rows.push([c.name, c.phone, c.address, c.email, '', dateStr, c.count]);
  }
  rows.sort(function(a, b) { return b[6] - a[6]; });
  if (rows.length > 0) cs.getRange(2, 1, rows.length, CUSTOMER_HEADERS.length).setValues(rows);
  Logger.log('Migrated ' + rows.length + ' unique customers.');
}

/* ============================================================
 * ONE-TIME SHEET SETUP HELPERS
 * ============================================================ */

/**
 * ONE-TIME SETUP — run this manually once from the Apps Script editor
 * (select "setupPaymentStatusDropdown" from the function dropdown at the
 * top, then click Run). This adds a dropdown to the Payment Status column
 * so you can quickly select a status instead of typing it.
 *
 * Safe to re-run any time — it just re-applies the same dropdown rule.
 */
function setupPaymentStatusDropdown() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var cm = buildColMap_(sheet, ORDER_COLS);
  var col = colLetter_(cm.paymentStatus);
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(['Pending', 'Paid', 'Refunded', 'Failed', 'Cancelled'], true)
    .setAllowInvalid(false)
    .build();
  sheet.getRange(col + '2:' + col + '1000').setDataValidation(rule);
  Logger.log('Payment Status dropdown applied to ' + col + '2:' + col + '1000');
}

/**
 * ONE-TIME SETUP — run once to add a dropdown to the Fulfillment Status column.
 */
function setupFulfillmentDropdown() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var cm = buildColMap_(sheet, ORDER_COLS);
  var col = colLetter_(cm.fulfillmentStatus);
  var rule = SpreadsheetApp.newDataValidation()
    .requireValueInList(['Packed', 'Booked', 'Picked Up', 'Delivered'], true)
    .setAllowInvalid(false)
    .build();
  sheet.getRange(col + '2:' + col + '1000').setDataValidation(rule);
  Logger.log('Fulfillment Status dropdown applied to ' + col + '2:' + col + '1000');
}

/* ============================================================
 * CLIENT ERROR LOG
 * ------------------------------------------------------------
 * The web app reports uncaught errors / unhandled rejections to
 * ?action=clientError. They land in an "ErrorLog" sheet tab so
 * silent client-side failures leave a durable trail. Capped at
 * the most recent 500 rows.
 * ============================================================ */
function logClientError_(p) {
  try {
    p = p || {};
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sh = ss.getSheetByName('ErrorLog');
    if (!sh) {
      sh = ss.insertSheet('ErrorLog');
      sh.appendRow(['Timestamp', 'User', 'Message', 'Context', 'Path', 'UserAgent']);
    }
    // If a valid token was sent, trust it for the username; otherwise fall back
    // to whatever the client claimed (best-effort, logged-out case).
    var payload = verifyToken_(p.auth);
    var user = payload ? payload.u : (p.user || '');
    sh.appendRow([
      new Date(),
      String(user).slice(0, 60),
      String(p.message || '').slice(0, 500),
      String(p.context || '').slice(0, 120),
      String(p.url || '').slice(0, 200),
      String(p.ua || '').slice(0, 300)
    ]);
    // Keep only the most recent 500 entries (row 1 is the header).
    var extra = sh.getLastRow() - 501;
    if (extra > 0) sh.deleteRows(2, extra);
    return jsonResponse({ status: 'success' });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

/* ============================================================
 * AUTOMATED BACKUP
 * ------------------------------------------------------------
 * Makes a timestamped copy of this whole spreadsheet (orders +
 * Customers + everything) into a "CCK Backups" Drive folder, and
 * keeps the most recent 30. Protects the single source of truth
 * from accidental deletion/corruption.
 *
 * ONE-TIME SETUP: run setupBackupTrigger() once from the editor
 * (grant Drive permission when prompted). It installs a daily
 * trigger; you can also run backupSpreadsheet() by hand any time.
 * ============================================================ */
var BACKUP_FOLDER = 'CCK Backups';
var BACKUP_KEEP = 30;

function backupSpreadsheet() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var file = DriveApp.getFileById(ss.getId());
  var folders = DriveApp.getFoldersByName(BACKUP_FOLDER);
  var folder = folders.hasNext() ? folders.next() : DriveApp.createFolder(BACKUP_FOLDER);
  var stamp = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd_HH-mm');
  file.makeCopy('CCK backup ' + stamp, folder);
  pruneBackups_(folder, BACKUP_KEEP);
}

function pruneBackups_(folder, keep) {
  var files = [];
  var it = folder.getFiles();
  while (it.hasNext()) files.push(it.next());
  files.sort(function (a, b) { return b.getDateCreated() - a.getDateCreated(); });
  for (var i = keep; i < files.length; i++) files[i].setTrashed(true);
}

function setupBackupTrigger() {
  // Remove any existing backup triggers so re-running doesn't stack duplicates.
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'backupSpreadsheet') {
      ScriptApp.deleteTrigger(triggers[i]);
    }
  }
  ScriptApp.newTrigger('backupSpreadsheet').timeBased().everyDays(1).atHour(2).create();
  backupSpreadsheet(); // take one immediately so there's a backup right away
  Logger.log('Daily backup trigger installed (runs ~2am) and a first backup was created.');
}
