// HTTP entry points — doPost and doGet.
// All write paths that append to the Orders sheet hold a script lock so
// concurrent webhook deliveries don't interleave rows.

function doPost(e) {
  try {
    var data = JSON.parse(e.postData.contents);

    if (data.action === 'login') {
      return login_(data.user || '', data.pass || '');
    }

    if (!verifyToken_(data.auth)) {
      return jsonResponse({ status: 'error', message: 'Unauthorized' });
    }

    if (data.action === 'uploadProof') {
      return uploadPaymentProof(data);
    }

    if (data.action === 'updateOrder') {
      var result = updateOrder(data);
      maybeBackupOnWrite_();
      return result;
    }

    if (data.action === 'saveCatalog') {
      return saveCatalog(data);
    }

    // New order creation — lock covers both the appendRow and the customer upsert
    // so concurrent submissions don't interleave rows in either sheet.
    var lock = LockService.getScriptLock();
    try {
      lock.waitLock(10000);
      var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
      if (sheet.getLastRow() === 0) {
        sheet.appendRow(ORDER_HEADERS);
      }
      sheet.appendRow(buildRow_({
        'Bill No':           data.billNo || '',
        'Date':              data.dateStr || '',
        'Customer Name':     data.name || '',
        'Phone':             data.phone || '',
        'Email':             data.email || '',
        'Address':           data.address || '',
        'Items Summary':     data.itemsSummary || '',
        'Total Items':       data.totalItems || 0,
        'Delivery Charges':  data.deliveryCharges || 0,
        'Total Amount':      data.totalAmount || 0,
        'Payment Status':    data.paymentStatus || 'Pending',
        'Dispatch Date':     data.dispatchDate || '',
        'Remarks':           data.remarks || '',
        'Generated By':      data.generatedBy || '',
        'Map Link':          data.mapLink || '',
        'Delivery Type':     data.deliveryType || '',
        'Share Token':       data.shareToken || '',
        'Discount':          data.discount || 0
        // Payment Proof, Fulfillment Status, Tracking Link start empty
      }));
      upsertCustomer(data.name || '', data.phone || '', data.email || '', data.address || '', data.dateStr || '');
    } finally {
      lock.releaseLock();
    }

    maybeBackupOnWrite_();
    return jsonResponse({ status: 'success' });
  } catch (err) {
    return jsonResponse({ status: 'error', message: err.toString() });
  }
}

function doGet(e) {
  var action = (e && e.parameter) ? e.parameter.action : null;

  // Public: customer-facing order tracking, scoped by per-order share token.
  if (action === 'getOrderByBill') {
    return getOrderByBill(e.parameter.billNo || '', e.parameter.token || '');
  }

  // Public: client error reporting (kept open so pre-login errors are captured).
  if (action === 'clientError') {
    return logClientError_(e.parameter);
  }

  var PROTECTED = { orders: 1, customers: 1, updateStatus: 1, updateFulfillment: 1, getCatalog: 1 };
  if (PROTECTED[action] && !verifyToken_(e.parameter.auth)) {
    return jsonResponse({ status: 'error', message: 'Unauthorized' });
  }

  if (action === 'orders') {
    return getOrders(e.parameter.search || '', parseInt(e.parameter.limit) || 50);
  }
  if (action === 'updateStatus') {
    return updateStatus(e.parameter.billNo || '', e.parameter.status || '');
  }
  if (action === 'updateFulfillment') {
    return updateFulfillment(
      e.parameter.billNo || '',
      e.parameter.fulfillmentStatus || '',
      e.parameter.trackingLink || ''
    );
  }
  if (action === 'customers') {
    return getCustomers();
  }
  if (action === 'getCatalog') {
    return getCatalog();
  }

  return ContentService.createTextOutput('CozyCatKitchen order logger is running.');
}

function jsonResponse(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}
