// Column definitions — single source of truth.
// See docs/SCHEMA.md for column meanings, types, and examples.
// These vars and helpers are pure (no GAS deps) and unit-tested in tests/.

var ORDER_COLS = {
  billNo:            'Bill No',
  date:              'Date',
  name:              'Customer Name',
  phone:             'Phone',
  email:             'Email',
  address:           'Address',
  itemsSummary:      'Items Summary',
  totalItems:        'Total Items',
  deliveryCharges:   'Delivery Charges',
  totalAmount:       'Total Amount',
  paymentStatus:     'Payment Status',
  dispatchDate:      'Dispatch Date',
  remarks:           'Remarks',
  generatedBy:       'Generated By',
  paymentProof:      'Payment Proof',
  fulfillmentStatus: 'Fulfillment Status',
  trackingLink:      'Tracking Link',
  mapLink:           'Map Link',
  deliveryType:      'Delivery Type',
  shareToken:        'Share Token'
};

// Optional columns: present only after running the corresponding setup helper.
// buildColMap_ returns null for these when missing instead of throwing.
var ORDER_OPTIONAL_COLS = {
  discount: 'Discount',
  dtdcAwb:  'DTDC AWB'
};

// Ordered header row written when a new sheet is initialised.
// Must contain every value from ORDER_COLS in the desired column order.
// Optional cols (ORDER_OPTIONAL_COLS) are appended at the end so existing
// sheets are not disturbed — run setupDiscountColumn() to add the header.
var ORDER_HEADERS = [
  'Bill No', 'Date', 'Customer Name', 'Phone', 'Email',
  'Address', 'Items Summary', 'Total Items', 'Delivery Charges',
  'Total Amount', 'Payment Status', 'Dispatch Date', 'Remarks', 'Generated By',
  'Payment Proof', 'Fulfillment Status', 'Tracking Link', 'Map Link', 'Delivery Type', 'Share Token',
  'Discount', 'DTDC AWB'
];

var CUSTOMER_COLS = {
  name:          'Name',
  phone:         'Phone',
  address:       'Address',
  email:         'Email',
  notes:         'Notes',
  lastOrderDate: 'LastOrderDate',
  totalOrders:   'TotalOrders'
};

var CUSTOMER_HEADERS = ['Name', 'Phone', 'Address', 'Email', 'Notes', 'LastOrderDate', 'TotalOrders'];

// Returns { fieldKey: 0-based-index } by reading the sheet's live header row.
// Throws if any required column (colDef) is absent.
// Optional columns (optColDef) get null in the map when missing instead of throwing.
function buildColMap_(sheet, colDef, optColDef) {
  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  var idx = {};
  for (var i = 0; i < headers.length; i++) {
    idx[String(headers[i]).trim()] = i;
  }
  var map = {};
  for (var key in colDef) {
    var h = colDef[key];
    if (!(h in idx)) {
      throw new Error('Column "' + h + '" not found in "' + sheet.getName() + '" — check docs/SCHEMA.md');
    }
    map[key] = idx[h];
  }
  if (optColDef) {
    for (var okey in optColDef) {
      var oh = optColDef[okey];
      map[okey] = (oh in idx) ? idx[oh] : null;
    }
  }
  return map;
}

// Converts a raw sheet row (array) to a plain order object.
function rowToOrder_(r, cm) {
  return {
    billNo:            r[cm.billNo],
    date:              r[cm.date],
    name:              r[cm.name],
    phone:             r[cm.phone],
    email:             r[cm.email],
    address:           r[cm.address],
    itemsSummary:      r[cm.itemsSummary],
    totalItems:        r[cm.totalItems],
    deliveryCharges:   r[cm.deliveryCharges],
    totalAmount:       r[cm.totalAmount],
    paymentStatus:     r[cm.paymentStatus],
    dispatchDate:      r[cm.dispatchDate],
    remarks:           r[cm.remarks],
    generatedBy:       r[cm.generatedBy],
    paymentProof:      r[cm.paymentProof],
    fulfillmentStatus: r[cm.fulfillmentStatus],
    trackingLink:      r[cm.trackingLink],
    mapLink:           r[cm.mapLink],
    deliveryType:      r[cm.deliveryType],
    shareToken:        r[cm.shareToken],
    discount:          cm.discount != null ? (Number(r[cm.discount]) || 0) : 0,
    dtdcAwb:           cm.dtdcAwb  != null ? String(r[cm.dtdcAwb]  || '') : ''
  };
}

// Builds an ordered array for appendRow() from { 'Header String': value }.
// Columns absent from the map default to ''.
function buildRow_(valuesByHeader) {
  return ORDER_HEADERS.map(function(h) {
    return h in valuesByHeader ? valuesByHeader[h] : '';
  });
}

// Converts a 0-based column index to a spreadsheet letter (A, B, …, AA, …).
function colLetter_(idx) {
  var letter = '';
  var n = idx + 1;
  while (n > 0) {
    var rem = (n - 1) % 26;
    letter = String.fromCharCode(65 + rem) + letter;
    n = Math.floor((n - 1) / 26);
  }
  return letter;
}
